apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-v1
  labels:
    app: flask-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
      version: v1
  template:
    metadata:
      labels:
        app: flask-app
        version: v1
    spec:
      containers:
        - name: flask-app
          image: jonasjoachim/flask-service:054b96dc68023c5dc060487e3ef0a7e46732c43a
          env:
            - name: VERSION
              value: "v1"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: flask-app-secret