apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-v1
  labels:
    app: flask-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
      version: v1
  template:
    metadata:
      labels:
        app: flask-app
        version: v1
    spec:
      containers:
        - name: flask-app
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          image: jonasjoachim/flask-service:latest
          env:
            - name: VERSION
              value: "v1"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: flask-app-secret