apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-v1
  labels:
    app: flask-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
      version: v1
  template:
    metadata:
      labels:
        app: flask-app
        version: v1
    spec:
      containers:
        - name: flask-app
          image: flask-app:v1
          imagePullPolicy: Never
          env:
            - name: VERSION
              value: "v1"
          ports:
            - containerPort: 80