apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-v1
  labels:
    app: httpbin
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      containers:
        - name: httpbin
          image: python:3.9-slim
          command: ["bash"]
          args: ["-c", "pip install flask && python /app/app.py"]
          env:
            - name: VERSION
              value: "v1"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /app
              name: app-code
      volumes:
        - name: app-code
          configMap:
            name: httpbin-app-code