apiVersion: v1
kind: Secret
metadata:
  name: flask-app-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJqb25hc2pvYWNoaW0iLCJwYXNzd29yZCI6ImRja3JfcGF0X29kejVnNUJHeWNvcVEtYllGT2hDN0ZLWFk1TSJ9fX0=
