apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - httpbin-gateway
  http:
    - route:
        - destination:
            host: httpbin-service
            subset: v1
          weight: 80
        - destination:
            host: httpbin-service
            subset: v2
          weight: 20